### PR TITLE
Add array sampling

### PR DESCRIPTION
**Pull request by mgold**
Like I said, merge in functions from [elm-random-sample](https://github.com/mgold/elm-random-sample) so we can have them in one place. Also converted them to produce generators, not manage seeds -- really liking that change -- and I'm ditching Trampoline in the hopes that TCO will work, even though it's actually two mutually recursive functions.

### CODE REVIEW

**Comment by mgold** [comment]
@rtfeldman Very kind of you to add non-employees to a company repo! Mind if I merge this and release a new minor version?

**Comment by rtfeldman** [comment]
Go for it! :+1:

**Comment by rtfeldman** [comment]
Honestly we only forked these because we depend on them for elm-check and wanted to update elm-check for 0.16, not because we have an active interest in contributing to/maintaining them...so in general, feel free to go for it whenever you feel a change will be good. :)

**Comment by mgold** [comment]
Well in that case you're welcome to hand them off to elm-community. You sure wanted to upgrade to 0.16 fast!

**Comment by rtfeldman** [comment]
Nothing to hand off, really...the only work on our end was in forking everything, updating them all to point to each other, and publishing again. If anyone wants to do that work again on elm-community, we'll happily deprecate this and switch to using that version!

**Pull request merged**
